version: 2
updates:
  - package-ecosystem: docker
    directory: "/containers"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
